"use client"

// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { Provider } from 'react-redux'
import { store } from '@/redux/store'

const montserrat = Montserrat({ subsets: ['latin'], weight: '600' })

// export const metadata: Metadata = {
//   title: 'Gutenberg Project',
//   description: 'A social cataloging website that allows you to freely search its database of books, annotations, and reviews.',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  )
}
